/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PostsIdPutRequest
 */
export interface V1PostsIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof V1PostsIdPutRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof V1PostsIdPutRequest
     */
    content: string;
}

/**
 * Check if a given object implements the V1PostsIdPutRequest interface.
 */
export function instanceOfV1PostsIdPutRequest(value: object): value is V1PostsIdPutRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function V1PostsIdPutRequestFromJSON(json: any): V1PostsIdPutRequest {
    return V1PostsIdPutRequestFromJSONTyped(json, false);
}

export function V1PostsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PostsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function V1PostsIdPutRequestToJSON(value?: V1PostsIdPutRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

