/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PostsIdGet200Response
 */
export interface V1PostsIdGet200Response {
    /**
     * 
     * @type {string}
     * @memberof V1PostsIdGet200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof V1PostsIdGet200Response
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof V1PostsIdGet200Response
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof V1PostsIdGet200Response
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof V1PostsIdGet200Response
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1PostsIdGet200Response
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the V1PostsIdGet200Response interface.
 */
export function instanceOfV1PostsIdGet200Response(value: object): value is V1PostsIdGet200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function V1PostsIdGet200ResponseFromJSON(json: any): V1PostsIdGet200Response {
    return V1PostsIdGet200ResponseFromJSONTyped(json, false);
}

export function V1PostsIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PostsIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'title': json['title'],
        'content': json['content'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function V1PostsIdGet200ResponseToJSON(value?: V1PostsIdGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'title': value['title'],
        'content': value['content'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

