/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UsersIdGet200Response
 */
export interface V1UsersIdGet200Response {
    /**
     * 
     * @type {string}
     * @memberof V1UsersIdGet200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof V1UsersIdGet200Response
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V1UsersIdGet200Response
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof V1UsersIdGet200Response
     */
    age: number;
    /**
     * 
     * @type {string}
     * @memberof V1UsersIdGet200Response
     */
    role: V1UsersIdGet200ResponseRoleEnum;
}


/**
 * @export
 */
export const V1UsersIdGet200ResponseRoleEnum = {
    Admin: 'admin',
    Editor: 'editor',
    Viewer: 'viewer'
} as const;
export type V1UsersIdGet200ResponseRoleEnum = typeof V1UsersIdGet200ResponseRoleEnum[keyof typeof V1UsersIdGet200ResponseRoleEnum];


/**
 * Check if a given object implements the V1UsersIdGet200Response interface.
 */
export function instanceOfV1UsersIdGet200Response(value: object): value is V1UsersIdGet200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function V1UsersIdGet200ResponseFromJSON(json: any): V1UsersIdGet200Response {
    return V1UsersIdGet200ResponseFromJSONTyped(json, false);
}

export function V1UsersIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UsersIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'age': json['age'],
        'role': json['role'],
    };
}

export function V1UsersIdGet200ResponseToJSON(value?: V1UsersIdGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'age': value['age'],
        'role': value['role'],
    };
}

