/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UsersPostRequest
 */
export interface V1UsersPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UsersPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V1UsersPostRequest
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof V1UsersPostRequest
     */
    age: number;
    /**
     * 
     * @type {string}
     * @memberof V1UsersPostRequest
     */
    role: V1UsersPostRequestRoleEnum;
}


/**
 * @export
 */
export const V1UsersPostRequestRoleEnum = {
    Admin: 'admin',
    Editor: 'editor',
    Viewer: 'viewer'
} as const;
export type V1UsersPostRequestRoleEnum = typeof V1UsersPostRequestRoleEnum[keyof typeof V1UsersPostRequestRoleEnum];


/**
 * Check if a given object implements the V1UsersPostRequest interface.
 */
export function instanceOfV1UsersPostRequest(value: object): value is V1UsersPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function V1UsersPostRequestFromJSON(json: any): V1UsersPostRequest {
    return V1UsersPostRequestFromJSONTyped(json, false);
}

export function V1UsersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UsersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'age': json['age'],
        'role': json['role'],
    };
}

export function V1UsersPostRequestToJSON(value?: V1UsersPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'age': value['age'],
        'role': value['role'],
    };
}

