/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PostsPostRequest
 */
export interface V1PostsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1PostsPostRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof V1PostsPostRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof V1PostsPostRequest
     */
    content: string;
}

/**
 * Check if a given object implements the V1PostsPostRequest interface.
 */
export function instanceOfV1PostsPostRequest(value: object): value is V1PostsPostRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function V1PostsPostRequestFromJSON(json: any): V1PostsPostRequest {
    return V1PostsPostRequestFromJSONTyped(json, false);
}

export function V1PostsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PostsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'title': json['title'],
        'content': json['content'],
    };
}

export function V1PostsPostRequestToJSON(value?: V1PostsPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'title': value['title'],
        'content': value['content'],
    };
}

