/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UsersIdPutRequest
 */
export interface V1UsersIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UsersIdPutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UsersIdPutRequest
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof V1UsersIdPutRequest
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof V1UsersIdPutRequest
     */
    role?: V1UsersIdPutRequestRoleEnum;
}


/**
 * @export
 */
export const V1UsersIdPutRequestRoleEnum = {
    Admin: 'admin',
    Editor: 'editor',
    Viewer: 'viewer'
} as const;
export type V1UsersIdPutRequestRoleEnum = typeof V1UsersIdPutRequestRoleEnum[keyof typeof V1UsersIdPutRequestRoleEnum];


/**
 * Check if a given object implements the V1UsersIdPutRequest interface.
 */
export function instanceOfV1UsersIdPutRequest(value: object): value is V1UsersIdPutRequest {
    return true;
}

export function V1UsersIdPutRequestFromJSON(json: any): V1UsersIdPutRequest {
    return V1UsersIdPutRequestFromJSONTyped(json, false);
}

export function V1UsersIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UsersIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'age': json['age'] == null ? undefined : json['age'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function V1UsersIdPutRequestToJSON(value?: V1UsersIdPutRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'age': value['age'],
        'role': value['role'],
    };
}

