/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  V1PostsIdGet200Response,
  V1PostsIdPutRequest,
  V1PostsPostRequest,
} from '../models/index';
import {
    V1PostsIdGet200ResponseFromJSON,
    V1PostsIdGet200ResponseToJSON,
    V1PostsIdPutRequestFromJSON,
    V1PostsIdPutRequestToJSON,
    V1PostsPostRequestFromJSON,
    V1PostsPostRequestToJSON,
} from '../models/index';

export interface V1PostsIdDeleteRequest {
    id: string;
}

export interface V1PostsIdGetRequest {
    id: string;
}

export interface V1PostsIdPutOperationRequest {
    id: string;
    v1PostsIdPutRequest?: V1PostsIdPutRequest;
}

export interface V1PostsPostOperationRequest {
    v1PostsPostRequest?: V1PostsPostRequest;
}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     */
    async v1PostsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<V1PostsIdGet200Response>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/posts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(V1PostsIdGet200ResponseFromJSON));
    }

    /**
     */
    async v1PostsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<V1PostsIdGet200Response>> {
        const response = await this.v1PostsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async v1PostsIdDeleteRaw(requestParameters: V1PostsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1PostsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async v1PostsIdDelete(requestParameters: V1PostsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PostsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async v1PostsIdGetRaw(requestParameters: V1PostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1PostsIdGet200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1PostsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1PostsIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1PostsIdGet(requestParameters: V1PostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1PostsIdGet200Response> {
        const response = await this.v1PostsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async v1PostsIdPutRaw(requestParameters: V1PostsIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1PostsIdGet200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1PostsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: V1PostsIdPutRequestToJSON(requestParameters['v1PostsIdPutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1PostsIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1PostsIdPut(requestParameters: V1PostsIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1PostsIdGet200Response> {
        const response = await this.v1PostsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async v1PostsPostRaw(requestParameters: V1PostsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1PostsIdGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/posts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1PostsPostRequestToJSON(requestParameters['v1PostsPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1PostsIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1PostsPost(requestParameters: V1PostsPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1PostsIdGet200Response> {
        const response = await this.v1PostsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
