/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  V1UsersIdGet200Response,
  V1UsersIdPutRequest,
  V1UsersPostRequest,
} from '../models/index';
import {
    V1UsersIdGet200ResponseFromJSON,
    V1UsersIdGet200ResponseToJSON,
    V1UsersIdPutRequestFromJSON,
    V1UsersIdPutRequestToJSON,
    V1UsersPostRequestFromJSON,
    V1UsersPostRequestToJSON,
} from '../models/index';

export interface V1UsersIdDeleteRequest {
    id: string;
}

export interface V1UsersIdGetRequest {
    id: string;
}

export interface V1UsersIdPutOperationRequest {
    id: string;
    v1UsersIdPutRequest?: V1UsersIdPutRequest;
}

export interface V1UsersPostOperationRequest {
    v1UsersPostRequest?: V1UsersPostRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     */
    async v1UsersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<V1UsersIdGet200Response>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(V1UsersIdGet200ResponseFromJSON));
    }

    /**
     */
    async v1UsersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<V1UsersIdGet200Response>> {
        const response = await this.v1UsersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async v1UsersIdDeleteRaw(requestParameters: V1UsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1UsersIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async v1UsersIdDelete(requestParameters: V1UsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1UsersIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async v1UsersIdGetRaw(requestParameters: V1UsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1UsersIdGet200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1UsersIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1UsersIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1UsersIdGet(requestParameters: V1UsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1UsersIdGet200Response> {
        const response = await this.v1UsersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async v1UsersIdPutRaw(requestParameters: V1UsersIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1UsersIdGet200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1UsersIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: V1UsersIdPutRequestToJSON(requestParameters['v1UsersIdPutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1UsersIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1UsersIdPut(requestParameters: V1UsersIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1UsersIdGet200Response> {
        const response = await this.v1UsersIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async v1UsersPostRaw(requestParameters: V1UsersPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1UsersIdGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1UsersPostRequestToJSON(requestParameters['v1UsersPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1UsersIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1UsersPost(requestParameters: V1UsersPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1UsersIdGet200Response> {
        const response = await this.v1UsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
